	INPUT	 	\PEDE AO USUÁRIO QUE ENTRE COM 1º VALOR
	STORE	X	\ARARMAZENA 1º VALOR NA MEMÓRIA
	INPUT		 \PEDE AO USUÁRIO QUE ENTRE COM 2º VALOR
	STORE	Y	 \ARMAZENA 2º VALOR NA MEMÓRIA
	LOAD	X	  \CARREGA 1º VALOR
	SUBT	Y	  \SUBTRAI COM O 2º VALOR
	
	SKIPCOND 400	   \SE A SUBTRAÇÃO DOS DOIS VALORES FOR IGUAL A 0, PULA PARA LOAD, SE NÃO, VAI PARA JUMP
	JUMP	SUB	   \JUMP SÓ SERÁ ATIVO QUANDO A SUBTRAÇÃO FOR DIFERENTE DE 0
MULT,	LOAD	X	   \FUNÇÃO MULTIPLICAÇÃO (CARREGA X)	
	ADD	X	    \(ADICIONA X)
	STORE	X	    \(ARMAZENA NOVO VALOR DE X)
	JUMP	FIM	     \FIM SE

SUB,	LOAD	Y	     \FUNÇÃO SUBTRAÇÃO - ATIVA QUANDO SUBTRAÇÃO DIFERENTE DE 0 (CARREGA Y)
	SUBT	X	     \(SUBTRAI X)
	STORE	Y	      \(ARMAZENA NOVO VALOR DE Y)

FIM,	OUTPUT		      \SAIDA DE VALOR NA TELA
	HALT		      \FINALIZA PROGRAMA

X,	DEC	0	       \VARIÁVEL DE X PARA USUÁRIO DECLARAR
Y,	DEC	0	       \VARIÁVEL DE Y PARA USUÁRIO DECLARAR