	ORG	000	\LOCAL DA MEMÓRIA
LOOP,	INPUT		 \PEDE PARA USUÁRIO DIGITAR VALOR
	STORE	A	 \ARMAZENA VARIÁVEL DO USUÁRIO
	LOAD	X	  \CARREGA VARIÁVEL DO SISTEMA 
	ADD	A	  \SOMA VARIÁVEL DO USUÁRIO(A) EM CIMA DO SITEMA(X) 	
	STORE	X	   \ARMAZENA ESSE NOVO RESULTADO OBTIDO EM CIMA DELA	

	LOAD	C	   \CARREGA UMA NOVA VARIÁVEL PARA CONTADOR
	SUBT	D	    \SUBTRAI 1 PARA A VARIÉVEL DO CONTADOR
	STORE	C	    \ARMAZENA A VARIÁVEL CONTADOR

	SKIPCOND 400	    \CONDIÇÃO PARA QUE SEJA =0 (ENQUANTO FOR MAIOR QUE 0 FICA EM LOOP, QUANDO ZERAR PULA O JUMP)
	JUMP	LOOP	     \LOOP 
	LOAD	X	     \ARMAZENA O VALOR QUE FINAL APÓS TODAS SOMA CONCLUÍDAS
	OUTPUT		     \EXIBI RESULTADO
	HALT		      \FINALIZA PROGRAMA	
	
X,	DEC	0	     \VARIÁVEL QUE VAI ARMAZENADO AS SOMAS
A,	DEC	0	      \VARIÁVEL QUE USUÁRIO ENTRA
C,	DEC	5	      \VARIÁVEL DO CONTADOR
D,	DEC	1	       \VARIÁVEL QUE DECRESCE ATÉ ZERAR